export const DEFAULT_SONG_CHIP = 'YM';
export const DEFAULT_SONG_FRAME = 50;
export const DEFAULT_SONG_CLOCK = 2000000;

export const SUPPORTED_SONG_CHIPS = [DEFAULT_SONG_CHIP];
export const SUPPORTED_SONG_FRAMES = [50, 60];
export const SUPPORTED_SONG_CLOCKS = [2000000, 1000000];
